In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("nba.csv.txt")
df

       team     player  points  assists  rebounds
0    Lakers     LeBron      28        8         7
1  Warriors      Curry      30        6         5
2     Bucks    Giannis      32        5        11
3   Celtics      Tatum      27        4         8
4      Suns     Booker      26        5         4
5    Lakers      Davis      24        3        10
6  Warriors   Thompson      22        2         3
7     Bucks  Middleton      20        4         6
8   Celtics      Brown      25        3         5
9      Suns     Durant      29        6         7

In [6]:
#Average Points Scored
df["points"].mean()

np.float64(26.3)

In [22]:
#Highest Scorer
print("Top Scorer:")
df[df["points"] == df["points"].max()]

Top Scorer:

    team   player  points  assists  rebounds
2  Bucks  Giannis      32        5        11

In [8]:
#Players that Scored at Least 25 Points
df[df["points"]>25]

       team   player  points  assists  rebounds
0    Lakers   LeBron      28        8         7
1  Warriors    Curry      30        6         5
2     Bucks  Giannis      32        5        11
3   Celtics    Tatum      27        4         8
4      Suns   Booker      26        5         4
9      Suns   Durant      29        6         7

In [23]:
#Average Player Points per Team
print("Average Points per Team:")
team_avg = df.groupby("team")["points"].mean()
team_avg

Average Points per Team:

team
Bucks       26.0
Celtics     26.0
Lakers      26.0
Suns        27.5
Warriors    26.0
Name: points, dtype: float64

In [26]:
#Team Rank by Scoring
print("Team Rank:")
team_avg.sort_values(ascending = False)

Team Rank:

team
Suns        27.5
Bucks       26.0
Celtics     26.0
Lakers      26.0
Warriors    26.0
Name: points, dtype: float64

In [20]:
print("Top Insight: Teams show small variation in average player scoring, with slight differences between rosters.")

Top Insight: Teams show small variation in average player scoring, with slight differences between rosters.